name: CI

on: [pull_request]

jobs:
  build-sdk:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build SDK
        run: |
          bash ./scripts/build.sh
  build-samples:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build samples
        run: |
          bash ./scripts/run_ci_tasks.sh samples
  run-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          bash ./scripts/run_ci_tasks.sh tests
  pod-lib-lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pod lint
        run: |
          bash ./scripts/run_ci_tasks.sh pod_lint
