name: CI

on: [pull_request]

jobs:
  build-sdk:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Build SDK
        run: |
          bash ./scripts/build.sh
  build-samples:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build samples
        run: |
          bash ./scripts/run_ci_tasks.sh samples
  run-tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bash ./scripts/run_ci_tasks.sh tests
  pod-lib-lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Pod lint
        run: |
          bash ./scripts/run_ci_tasks.sh pod_lint
